inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_fixme.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'docs/**/*'
    - 'scripts/**/*'
    - 'tmp/**/*'

Metrics/AbcSize:
  Exclude:
    - 'app/prepends/prepended_services/exhibit_import_export_service.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/prepends/prepended_services/exhibit_import_export_service.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/prepends/prepended_services/exhibit_import_export_service.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/prepends/prepended_services/exhibit_import_export_service.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/prepends/prepended_services/exhibit_import_export_service.rb'

Metrics/BlockLength:
  ExcludedMethods: ['included']
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'
    - 'db/schema.rb'
    - 'Rakefile'
    - '*.gemspec'
    - 'config/routes.rb'

# Naming/FileName: # https://github.com/bbatsov/rubocop/issues/2973
#   Exclude:
#     - 'Gemfile'

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

# disable frozen string literal comment. We can't safely introduce this
# system-wide until a major version because it freezes strings that downstream
# users might be mutating. Please use the frozen string literal pragma on new
# files
Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

# We define custom methods like `find_by_user_key`,
# `find_by_created_date`, etc
Rails/DynamicFindBy:
  Enabled: false

# # By default RSpec/MessageSpies has the following:
# #   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# # The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false
