# Place any default configuration for solr_wrapper here
# https://github.com/cbeer/solr_wrapper#valid-ruby-and-yaml-options
version: '8.11.2'
collection:
  dir: solr/conf/
  name: blacklight-core
  persist: true
