# Docker compose file for test environment
# Run with: docker compose -f compose.test.yaml up

services:
  webapp:
    build:
      context: .
      target: test
    image: exhibits-test
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - PORT=3010
    volumes:
      - .:/exhibits
    ports:
      - 3010:3010
    depends_on:
      - mysql
      - redis
      - solr
      - chrome

  solr:
    extends:
      file: compose.base.yaml
      service: solr
    ports:
      - 8984:8983

  redis:
    extends:
      file: compose.base.yaml
      service: redis
    ports:
      - 6479:6379

  chrome:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444

  mysql:
    extends:
      file: compose.base.yaml
      service: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_RAILS_ROOT_PW}
      - MYSQL_USER=${DATABASE_RAILS_USER}
      - MYSQL_PASSWORD=${DATABASE_RAILS_USER_PW}
      - MYSQL_DATABASE=${DATABASE_NAME_PREFIX}_test
    ports:
      - 3307:3307
