# Docker compose file for integration environment
# Run with: docker compose -f compose.integration.yaml up
#
# For local development testing of the integration container:
# consider setting up a redis container, instead of connecting to the remote redis host.

services:
  webapp:
    # Set platform to linux/amd64 when building on ARM based system to push to ECR
    # platform: linux/amd64
    build:
      context: .
      args:
        BUNDLE_WITHOUT: "development test"
        RACK_ENV: integration
        RAILS_ENV: integration
    image: exhibits_integration
    stdin_open: true
    tty: true
    environment:
      - PORT=9292
    ports:
      - 9292:9292
