default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['DATABASE_RAILS_USER'] %>
  password: <%= ENV['DATABASE_RAILS_USER_PW'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME_PREFIX'] %>_development

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME_PREFIX'] %>_test

integration:
  <<: *default
  database: <%= ENV['DATABASE_NAME_PREFIX'] %>_integration
  socket: /var/lib/mysql/mysql.sock

staging:
  <<: *default
  database: <%= ENV['DATABASE_NAME_PREFIX'] %>_staging
  socket: /var/lib/mysql/mysql.sock

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME_PREFIX'] %>
  socket: /var/lib/mysql/mysql.sock
