source "https://rubygems.org"

gem 'ffi'
gem 'github-pages' # plugins will not run if group: :jekyll_plugins is used
gem 'html-proofer'
gem "jekyll", "~> 3"
gem 'rake'
gem 'nokogiri'
gem 'rubyzip'
gem 'webrick' # required for ruby3

group :development, :test do
  gem "rspec"
  gem "selenium-webdriver"
  gem "webdrivers"
  gem "capybara"
  gem 'launchy'
  gem "pry-byebug"
  gem 'rspec_junit_formatter'
end
